name: evo_med
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  dio: ^5.4.1
  get_it: ^7.6.7
  flutter_svg: ^2.0.10+1
  mask_text_input_formatter: ^2.9.0
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  formz: ^0.7.0
  go_router: ^13.2.0
  gap: ^3.0.1
  path_provider: ^2.0.5
  easy_localization: ^3.0.5
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  gradient_borders: ^1.0.1
  keyboard_dismisser: ^3.0.0
  dots_indicator: ^4.0.1
  syncfusion_flutter_signaturepad: 27.2.5
  pinput: ^5.0.0
  expandable_page_view: ^1.0.17
  geolocator: ^13.0.4
  device_info_plus: ^11.3.0
  local_auth: ^2.3.0
  myid: ^1.3.4

  nirikshak:

  # Forked because of the issue with ios build
  # Swift Compiler Error (Xcode): Cannot find 'TARGET_IPHONE_SIMULATOR' in scope
  yandex_mapkit:
    git:
      url: https://github.com/Muhammadyunusxon/yandex_mapkit.git
      ref: master

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  dart_style: ^2.3.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/dummy/
    - assets/icons/
    - assets/fonts/
    - assets/translations/

  fonts:
    - family: NT Somic
      fonts:
        - asset: assets/fonts/NTSomic-Regular.ttf
        - asset: assets/fonts/NTSomic-Medium.ttf
        - asset: assets/fonts/NTSomic-Semibold.ttf
        - asset: assets/fonts/NTSomic-Bold.ttf

  



          
    